version: '3'

services:
  fastapi_app:
    build:
      context: APIv2
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./APIv2:/app

  bot:
    build:
      context: BOTv2
      dockerfile: Dockerfile
    volumes:
      - ./BOTv2:/app
